---
# CI code for testing SaltStack Netdata scripts
name: SaltStack
on:
  push:
    branches:
      - test

jobs:
  Test:
    name: Test Salt
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         image:
#           - 'ubuntu2004'
#           - 'centos7'
#           - 'centos8'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Read File
        run: |
          import yaml
          
          with open('servers.yml') as file:
            data = yaml.load(file, Loader=yaml.FullLoader)
          vm_list=[]
          for i in data:
            vm_list.append(i["name"])
          print(vm_list)
          
        shell: python
