---
# CI code for testing SaltStack Netdata scripts
name: SaltStack
on:
  push:
    branches:
      - test

jobs:
  build-matrix:
    name: Build
    runs-on: ubuntu-latest
    outputs: 
      version_matrix: ${{ steps.set-matrix.outputs.version_matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Read File
        id: set-matrix
        run: |
          import yaml
          with open('servers.yml') as file:
            data = yaml.load(file, Loader=yaml.FullLoader)
            vm_list=[]
            for i in data:
              vm_list.append(i["name"])
            print(f"::set-output name=version_matrix::{vm_list}")
            #run: echo "::set-output name=version_matrix::$(ls|jq -cnR '[inputs | select(length>0)]')"
          
        shell: python

  Test:
    needs: build-matrix
    name: test
    runs-on: ubuntu-latest
    steps:
      - name : AA
        run: |
          param=${{ needs.build-matrix.outputs.version_matrix}}
          echo ${param}
    #strategy:
      #matrix:
        #versions: $param

